twilio-security-tests:
    timeout: 30m
    type: instrumentation
    app: ftl/dummy.apk
    test: {{test_build}}
    device:
        # Pixel3
        - {model: blueline, version: 28, locale: en, orientation: portrait}
        # Pixel 5e
        - {model: redfin, version: 30, locale: en, orientation: portrait}
        # Google Oriole
        - {model: oriole, version: 31, locale: en, orientation: portrait}
        # Pixel 7
        - {model: panther, version: 33, locale: en, orientation: portrait}
